CREATE TABLE IF NOT EXISTS RAW_HANDS (
    HAND_ID STRING,
    SOURCE_RUN_ID STRING,
    SOURCE_TYPE STRING,
    SOURCE_DATASET STRING,
    SIMULATION_RUN_ID STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    HERO_SEAT NUMBER(38,0),
    TABLE_ID STRING,
    BUTTON_SEAT NUMBER(38,0),
    BIG_BLIND_BB FLOAT,
    SMALL_BLIND_BB FLOAT,
    TOTAL_POT_BB FLOAT,
    BOARD_CARDS STRING,
    STARTED_AT TIMESTAMP_NTZ,
    FINISHED_AT TIMESTAMP_NTZ,
    PAYLOAD_VERSION STRING,
    RAW_LINEAGE VARIANT
);

CREATE TABLE IF NOT EXISTS RAW_ACTIONS (
    HAND_ID STRING,
    ACTION_INDEX NUMBER(38,0),
    SOURCE_RUN_ID STRING,
    SOURCE_TYPE STRING,
    SOURCE_DATASET STRING,
    SIMULATION_RUN_ID STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    HERO_SEAT NUMBER(38,0),
    IS_HERO_PLAYER BOOLEAN,
    TABLE_ID STRING,
    STREET STRING,
    PLAYER_ID STRING,
    AGENT_ID STRING,
    SEAT NUMBER(38,0),
    POSITION STRING,
    ACTION_TYPE STRING,
    AMOUNT_BB FLOAT,
    POT_BEFORE_BB FLOAT,
    POT_AFTER_BB FLOAT,
    TO_CALL_BB FLOAT,
    EFFECTIVE_STACK_BB FLOAT,
    PLAYERS_REMAINING NUMBER(38,0),
    BOARD_CARDS_VISIBLE STRING,
    HOLE_CARDS_VISIBLE STRING,
    IS_ALL_IN BOOLEAN,
    EVENT_TS TIMESTAMP_NTZ,
    BACKEND_TYPE STRING,
    PERSONA_NAME STRING,
    PERSONA_TEXT STRING,
    PAYLOAD_VERSION STRING,
    RAW_LINEAGE VARIANT
);

CREATE TABLE IF NOT EXISTS RAW_PLAYERS (
    SOURCE_RUN_ID STRING,
    SOURCE_TYPE STRING,
    SOURCE_DATASET STRING,
    SIMULATION_RUN_ID STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    HERO_SEAT NUMBER(38,0),
    IS_HERO_PLAYER BOOLEAN,
    TABLE_ID STRING,
    HAND_ID STRING,
    PLAYER_ID STRING,
    AGENT_ID STRING,
    SEAT NUMBER(38,0),
    PLAYER_NAME STRING,
    STACK_START_BB FLOAT,
    STACK_END_BB FLOAT,
    HOLE_CARDS STRING,
    RESULT_BB FLOAT,
    BACKEND_TYPE STRING,
    PERSONA_NAME STRING,
    PERSONA_TEXT STRING,
    MADE_SHOWDOWN BOOLEAN,
    SHOWDOWN_HAND_CATEGORY STRING,
    SHOWDOWN_HAND_SCORE FLOAT,
    PAYLOAD_VERSION STRING,
    RAW_LINEAGE VARIANT
);

CREATE TABLE IF NOT EXISTS RAW_SIMULATION_RUNS (
    SIMULATION_RUN_ID STRING,
    TABLE_ID STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    BACKEND_TYPE STRING,
    STATUS STRING,
    REQUEST_MODE STRING,
    REQUESTED_AT TIMESTAMP_NTZ,
    STARTED_AT TIMESTAMP_NTZ,
    FINISHED_AT TIMESTAMP_NTZ,
    HAND_COUNT NUMBER(38,0),
    SEED NUMBER(38,0),
    HERO_CONTEXT STRING,
    HERO_SEAT NUMBER(38,0),
    MODEL_NAME STRING,
    ERROR_MESSAGE STRING,
    PUBLISHED_ACTIONS NUMBER(38,0),
    PUBLISHED_HAND_SUMMARIES NUMBER(38,0),
    CONFIG_JSON VARIANT
);

ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS STATUS STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS REQUEST_MODE STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS REQUESTED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS HERO_CONTEXT STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS MODEL_NAME STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS ERROR_MESSAGE STRING;
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS PUBLISHED_ACTIONS NUMBER(38,0);
ALTER TABLE RAW_SIMULATION_RUNS ADD COLUMN IF NOT EXISTS PUBLISHED_HAND_SUMMARIES NUMBER(38,0);
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS BUTTON_SEAT NUMBER(38,0);
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS BIG_BLIND_BB FLOAT;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS SMALL_BLIND_BB FLOAT;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS TOTAL_POT_BB FLOAT;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS BOARD_CARDS STRING;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS STARTED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS FINISHED_AT TIMESTAMP_NTZ;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE RAW_HANDS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS HAND_ID STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS ACTION_INDEX NUMBER(38,0);
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_RUN_ID STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_TYPE STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_DATASET STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS STREET STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS SEAT NUMBER(38,0);
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS POSITION STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS ACTION_TYPE STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS AMOUNT_BB FLOAT;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS POT_BEFORE_BB FLOAT;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS POT_AFTER_BB FLOAT;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS TO_CALL_BB FLOAT;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS EFFECTIVE_STACK_BB FLOAT;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS PLAYERS_REMAINING NUMBER(38,0);
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS BOARD_CARDS_VISIBLE STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS HOLE_CARDS_VISIBLE STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS IS_ALL_IN BOOLEAN;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS EVENT_TS TIMESTAMP_NTZ;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS BACKEND_TYPE STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS PERSONA_TEXT STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE RAW_ACTIONS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_RUN_ID STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_TYPE STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_DATASET STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS HAND_ID STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS SEAT NUMBER(38,0);
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS PLAYER_NAME STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS STACK_START_BB FLOAT;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS STACK_END_BB FLOAT;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS HOLE_CARDS STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS RESULT_BB FLOAT;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS BACKEND_TYPE STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS PERSONA_TEXT STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS MADE_SHOWDOWN BOOLEAN;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS SHOWDOWN_HAND_CATEGORY STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS SHOWDOWN_HAND_SCORE FLOAT;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE RAW_PLAYERS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;

CREATE TABLE IF NOT EXISTS SIMULATION_RUN_PLAYER_SUMMARIES (
    SIMULATION_RUN_ID STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    IS_HERO_PLAYER BOOLEAN,
    SEAT NUMBER(38,0),
    PLAYER_ID STRING,
    AGENT_ID STRING,
    PERSONA_NAME STRING,
    BACKEND_TYPE STRING,
    HANDS_PLAYED NUMBER(38,0),
    TOTAL_BB_WON FLOAT,
    AVG_BB_PER_HAND FLOAT,
    BB_PER_100 FLOAT,
    STACK_RESET_COUNT NUMBER(38,0),
    LLM_DECISION_COUNT NUMBER(38,0),
    HEURISTIC_DECISION_COUNT NUMBER(38,0),
    LLM_FALLBACK_COUNT NUMBER(38,0),
    FINAL_RANK NUMBER(38,0),
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS CURATED_HANDS LIKE RAW_HANDS;
CREATE TABLE IF NOT EXISTS CURATED_ACTIONS LIKE RAW_ACTIONS;
CREATE TABLE IF NOT EXISTS CURATED_PLAYERS LIKE RAW_PLAYERS;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS BUTTON_SEAT NUMBER(38,0);
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS BIG_BLIND_BB FLOAT;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS SMALL_BLIND_BB FLOAT;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS TOTAL_POT_BB FLOAT;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS BOARD_CARDS STRING;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS STARTED_AT TIMESTAMP_NTZ;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS FINISHED_AT TIMESTAMP_NTZ;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE CURATED_HANDS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS HAND_ID STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS ACTION_INDEX NUMBER(38,0);
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_RUN_ID STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_TYPE STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_DATASET STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS STREET STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS SEAT NUMBER(38,0);
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS POSITION STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS ACTION_TYPE STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS AMOUNT_BB FLOAT;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS POT_BEFORE_BB FLOAT;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS POT_AFTER_BB FLOAT;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS TO_CALL_BB FLOAT;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS EFFECTIVE_STACK_BB FLOAT;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS PLAYERS_REMAINING NUMBER(38,0);
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS BOARD_CARDS_VISIBLE STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS HOLE_CARDS_VISIBLE STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS IS_ALL_IN BOOLEAN;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS EVENT_TS TIMESTAMP_NTZ;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS BACKEND_TYPE STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS PERSONA_TEXT STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE CURATED_ACTIONS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_RUN_ID STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_TYPE STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_DATASET STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS HAND_ID STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS SEAT NUMBER(38,0);
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS PLAYER_NAME STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS STACK_START_BB FLOAT;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS STACK_END_BB FLOAT;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS HOLE_CARDS STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS RESULT_BB FLOAT;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS BACKEND_TYPE STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS PERSONA_TEXT STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS MADE_SHOWDOWN BOOLEAN;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS SHOWDOWN_HAND_CATEGORY STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS SHOWDOWN_HAND_SCORE FLOAT;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE CURATED_PLAYERS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;

CREATE STAGE IF NOT EXISTS HISTORICAL_HANDHQ_STAGE;

CREATE TABLE IF NOT EXISTS HISTORICAL_HANDHQ_LANDING_HANDS LIKE RAW_HANDS;
CREATE TABLE IF NOT EXISTS HISTORICAL_HANDHQ_LANDING_ACTIONS LIKE RAW_ACTIONS;
CREATE TABLE IF NOT EXISTS HISTORICAL_HANDHQ_LANDING_PLAYERS LIKE RAW_PLAYERS;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS BUTTON_SEAT NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS BIG_BLIND_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS SMALL_BLIND_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS TOTAL_POT_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS BOARD_CARDS STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS STARTED_AT TIMESTAMP_NTZ;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS FINISHED_AT TIMESTAMP_NTZ;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_HANDS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS HAND_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS ACTION_INDEX NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_RUN_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_TYPE STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS SOURCE_DATASET STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS STREET STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS SEAT NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS POSITION STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS ACTION_TYPE STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS AMOUNT_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS POT_BEFORE_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS POT_AFTER_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS TO_CALL_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS EFFECTIVE_STACK_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS PLAYERS_REMAINING NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS BOARD_CARDS_VISIBLE STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS HOLE_CARDS_VISIBLE STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS IS_ALL_IN BOOLEAN;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS EVENT_TS TIMESTAMP_NTZ;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS BACKEND_TYPE STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS PERSONA_TEXT STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_ACTIONS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_RUN_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_TYPE STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS SOURCE_DATASET STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS SIMULATION_RUN_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS HERO_SEAT NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS TABLE_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS HAND_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS SEAT NUMBER(38,0);
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS PLAYER_NAME STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS STACK_START_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS STACK_END_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS HOLE_CARDS STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS RESULT_BB FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS BACKEND_TYPE STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS PERSONA_TEXT STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS MADE_SHOWDOWN BOOLEAN;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS SHOWDOWN_HAND_CATEGORY STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS SHOWDOWN_HAND_SCORE FLOAT;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS PAYLOAD_VERSION STRING;
ALTER TABLE HISTORICAL_HANDHQ_LANDING_PLAYERS ADD COLUMN IF NOT EXISTS RAW_LINEAGE VARIANT;

CREATE TABLE IF NOT EXISTS HISTORICAL_HANDHQ_INGEST_RUNS (
    SOURCE_RUN_ID STRING,
    SOURCE_URI STRING,
    SOURCE_DATASET STRING,
    STAGE_NAME STRING,
    STAGE_PREFIX STRING,
    STATUS STRING,
    STARTED_AT TIMESTAMP_NTZ,
    FINISHED_AT TIMESTAMP_NTZ,
    DISCOVERED_FILES NUMBER(38,0),
    SKIPPED_FILES NUMBER(38,0),
    PROCESSED_FILES NUMBER(38,0),
    FAILED_FILES NUMBER(38,0),
    REJECTED_FILES NUMBER(38,0),
    LOADED_HANDS NUMBER(38,0),
    REJECTED_HANDS NUMBER(38,0),
    RAW_HAND_ROWS NUMBER(38,0),
    RAW_PLAYER_ROWS NUMBER(38,0),
    RAW_ACTION_ROWS NUMBER(38,0),
    MESSAGE STRING
);

CREATE TABLE IF NOT EXISTS HISTORICAL_HANDHQ_INGEST_FILES (
    CONTENT_HASH STRING,
    SOURCE_RUN_ID STRING,
    SOURCE_FILE STRING,
    SOURCE_DATASET STRING,
    STATUS STRING,
    FILE_SIZE_BYTES NUMBER(38,0),
    DISCOVERED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    HANDS_SEEN NUMBER(38,0),
    HANDS_LOADED NUMBER(38,0),
    HANDS_REJECTED NUMBER(38,0),
    RAW_HAND_ROWS NUMBER(38,0),
    RAW_PLAYER_ROWS NUMBER(38,0),
    RAW_ACTION_ROWS NUMBER(38,0),
    LAST_ERROR STRING
);

CREATE TABLE IF NOT EXISTS LIVE_AGENT_METRICS (
    METRIC_WINDOW_START TIMESTAMP_NTZ,
    METRIC_WINDOW_END TIMESTAMP_NTZ,
    SIMULATION_RUN_ID STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    IS_HERO_PLAYER BOOLEAN,
    AGENT_ID STRING,
    PLAYER_ID STRING,
    PERSONA_NAME STRING,
    ACTIONS_PER_SECOND FLOAT,
    HANDS_PER_SECOND FLOAT,
    VPIP FLOAT,
    PFR FLOAT,
    AGGRESSION_FREQUENCY FLOAT,
    CBET_RATE FLOAT,
    ALL_IN_RATE FLOAT,
    BB_WON FLOAT,
    OBSERVED_HANDS NUMBER(38,0),
    OBSERVED_ACTIONS NUMBER(38,0),
    UPDATED_AT TIMESTAMP_NTZ
);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS SEAT NUMBER(38,0);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS BACKEND_TYPE STRING;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS HANDS_PLAYED NUMBER(38,0);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS TOTAL_BB_WON FLOAT;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS AVG_BB_PER_HAND FLOAT;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS BB_PER_100 FLOAT;
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS STACK_RESET_COUNT NUMBER(38,0);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS LLM_DECISION_COUNT NUMBER(38,0);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS HEURISTIC_DECISION_COUNT NUMBER(38,0);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS LLM_FALLBACK_COUNT NUMBER(38,0);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS FINAL_RANK NUMBER(38,0);
ALTER TABLE SIMULATION_RUN_PLAYER_SUMMARIES ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS PERSONA_NAME STRING;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS ACTIONS_PER_SECOND FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS HANDS_PER_SECOND FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS VPIP FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS PFR FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS AGGRESSION_FREQUENCY FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS CBET_RATE FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS ALL_IN_RATE FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS BB_WON FLOAT;
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS OBSERVED_HANDS NUMBER(38,0);
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS OBSERVED_ACTIONS NUMBER(38,0);
ALTER TABLE LIVE_AGENT_METRICS ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;

CREATE TABLE IF NOT EXISTS LIVE_PROFILE_ASSIGNMENTS (
    SIMULATION_RUN_ID STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    IS_HERO_PLAYER BOOLEAN,
    AGENT_ID STRING,
    PLAYER_ID STRING,
    NEAREST_CLUSTER_ID NUMBER(38,0),
    NEAREST_CLUSTER_LABEL STRING,
    DISTANCE_TO_CENTROID FLOAT,
    ASSIGNED_AT TIMESTAMP_NTZ
);
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS IS_HERO_PLAYER BOOLEAN;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS AGENT_ID STRING;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS PLAYER_ID STRING;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS NEAREST_CLUSTER_ID NUMBER(38,0);
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS NEAREST_CLUSTER_LABEL STRING;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS DISTANCE_TO_CENTROID FLOAT;
ALTER TABLE LIVE_PROFILE_ASSIGNMENTS ADD COLUMN IF NOT EXISTS ASSIGNED_AT TIMESTAMP_NTZ;

CREATE TABLE IF NOT EXISTS DASHBOARD_SUMMARIES (
    SUMMARY_KEY STRING,
    SUMMARY_SCOPE STRING,
    USER_ID STRING,
    DECISION_BACKEND STRING,
    HERO_CONTEXT_HASH STRING,
    SUMMARY_JSON VARIANT,
    UPDATED_AT TIMESTAMP_NTZ
);
ALTER TABLE DASHBOARD_SUMMARIES ADD COLUMN IF NOT EXISTS USER_ID STRING;
ALTER TABLE DASHBOARD_SUMMARIES ADD COLUMN IF NOT EXISTS DECISION_BACKEND STRING;
ALTER TABLE DASHBOARD_SUMMARIES ADD COLUMN IF NOT EXISTS HERO_CONTEXT_HASH STRING;
ALTER TABLE DASHBOARD_SUMMARIES ADD COLUMN IF NOT EXISTS SUMMARY_JSON VARIANT;
ALTER TABLE DASHBOARD_SUMMARIES ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP_NTZ;

CREATE TABLE IF NOT EXISTS PROFILE_PLAYER_HAND_FEATURES (
    TRAINING_DATASET STRING,
    FEATURE_VERSION STRING,
    SOURCE_TYPE STRING,
    SOURCE_DATASET STRING,
    SOURCE_RUN_ID STRING,
    SIMULATION_RUN_ID STRING,
    TABLE_ID STRING,
    HAND_ID STRING,
    PLAYER_ID STRING,
    AGENT_ID STRING,
    POSITION STRING,
    STACK_START_BB FLOAT,
    PREFLOP_VPIP BOOLEAN,
    PREFLOP_PFR BOOLEAN,
    AGGRESSIVE_ACTIONS NUMBER(38,0),
    PASSIVE_ACTIONS NUMBER(38,0),
    PREFLOP_AGGRESSIVE_AMOUNT_TOTAL_BB FLOAT,
    PREFLOP_AGGRESSIVE_ACTION_COUNT NUMBER(38,0),
    POSTFLOP_AGGRESSIVE_BET_POT_RATIO_SUM FLOAT,
    POSTFLOP_AGGRESSIVE_BET_COUNT NUMBER(38,0),
    SAW_FLOP BOOLEAN,
    SAW_TURN BOOLEAN,
    SAW_RIVER BOOLEAN,
    ALL_IN BOOLEAN,
    CBET_OPPORTUNITY_FLOP BOOLEAN,
    FLOP_CBET BOOLEAN,
    TURN_BARREL_OPPORTUNITY BOOLEAN,
    TURN_BARREL BOOLEAN,
    LATE_POSITION_HAND BOOLEAN,
    LATE_POSITION_VPIP BOOLEAN,
    BLIND_POSITION_HAND BOOLEAN,
    BLIND_DEFEND BOOLEAN,
    SHORT_STACK_HAND BOOLEAN,
    SHORT_STACK_AGGRESSIVE_ACTIONS NUMBER(38,0),
    SHORT_STACK_PASSIVE_ACTIONS NUMBER(38,0),
    DEEP_STACK_HAND BOOLEAN,
    DEEP_STACK_VPIP BOOLEAN,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS PROFILE_PLAYER_TRAINING_FEATURES (
    TRAINING_DATASET STRING,
    FEATURE_VERSION STRING,
    PLAYER_ID STRING,
    SOURCE_DATASET STRING,
    HANDS_PLAYED NUMBER(38,0),
    AGGRESSIVE_ACTIONS NUMBER(38,0),
    PASSIVE_ACTIONS NUMBER(38,0),
    FLOP_CBET_OPPORTUNITIES NUMBER(38,0),
    TURN_BARREL_OPPORTUNITIES NUMBER(38,0),
    LATE_POSITION_HANDS NUMBER(38,0),
    BLIND_POSITION_HANDS NUMBER(38,0),
    SHORT_STACK_HANDS NUMBER(38,0),
    DEEP_STACK_HANDS NUMBER(38,0),
    VPIP_RATE FLOAT,
    PFR_RATE FLOAT,
    AGGRESSION_FREQUENCY FLOAT,
    CALL_PREFERENCE FLOAT,
    FLOP_CBET_RATE FLOAT,
    TURN_BARREL_RATE FLOAT,
    RIVER_SEEN_RATE FLOAT,
    ALL_IN_RATE FLOAT,
    AVG_PREFLOP_RAISE_BB FLOAT,
    AVG_POSTFLOP_BET_POT_RATIO FLOAT,
    LATE_POSITION_VPIP_RATE FLOAT,
    BLIND_DEFEND_RATE FLOAT,
    SHORT_STACK_AGGRESSION_RATE FLOAT,
    DEEP_STACK_LOOSENESS FLOAT,
    ELIGIBLE_FOR_TRAINING BOOLEAN,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS PROFILE_MODEL_RUNS (
    MODEL_RUN_ID STRING,
    CREATED_AT TIMESTAMP_NTZ,
    ACTIVATED_AT TIMESTAMP_NTZ,
    ACTIVE BOOLEAN,
    ALGORITHM STRING,
    CLUSTER_COUNT NUMBER(38,0),
    TRAINING_DATASET STRING,
    FEATURE_VERSION STRING,
    TRAINING_PLAYER_COUNT NUMBER(38,0),
    MIN_HAND_THRESHOLD NUMBER(38,0),
    PARAMETERS_JSON VARIANT,
    SELECTION_METRICS_JSON VARIANT,
    STATUS STRING
);

CREATE TABLE IF NOT EXISTS PROFILE_MODEL_FEATURES (
    MODEL_RUN_ID STRING,
    FEATURE_NAME STRING,
    FEATURE_ORDER NUMBER(38,0),
    FEATURE_VERSION STRING,
    SCALER_MEAN FLOAT,
    SCALER_SCALE FLOAT,
    GLOBAL_MEAN FLOAT,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS PROFILE_CLUSTER_CENTROIDS (
    MODEL_RUN_ID STRING,
    CLUSTER_ID NUMBER(38,0),
    CLUSTER_LABEL STRING,
    SUMMARY_TEXT STRING,
    CLUSTER_SIZE NUMBER(38,0),
    CLUSTER_SHARE FLOAT,
    CENTROID_JSON VARIANT,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS PROFILE_CLUSTER_PROTOTYPES (
    MODEL_RUN_ID STRING,
    CLUSTER_ID NUMBER(38,0),
    PROTOTYPE_RANK NUMBER(38,0),
    PLAYER_ID STRING,
    SOURCE_DATASET STRING,
    HANDS_PLAYED NUMBER(38,0),
    DISTANCE_TO_CENTROID FLOAT,
    PROTOTYPE_JSON VARIANT,
    UPDATED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS PROFILE_HISTORICAL_ASSIGNMENTS (
    MODEL_RUN_ID STRING,
    PLAYER_ID STRING,
    SOURCE_DATASET STRING,
    CLUSTER_ID NUMBER(38,0),
    CLUSTER_LABEL STRING,
    DISTANCE_TO_CENTROID FLOAT,
    HANDS_PLAYED NUMBER(38,0),
    ASSIGNED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS PROFILE_SESSION_FEATURES (
    MODEL_RUN_ID STRING,
    FEATURE_VERSION STRING,
    SOURCE_TYPE STRING,
    SOURCE_DATASET STRING,
    SOURCE_RUN_ID STRING,
    SIMULATION_RUN_ID STRING,
    SUBJECT_ID STRING,
    PLAYER_ID STRING,
    AGENT_ID STRING,
    HANDS_OBSERVED NUMBER(38,0),
    AGGRESSIVE_ACTIONS NUMBER(38,0),
    PASSIVE_ACTIONS NUMBER(38,0),
    FLOP_CBET_OPPORTUNITIES NUMBER(38,0),
    TURN_BARREL_OPPORTUNITIES NUMBER(38,0),
    LATE_POSITION_HANDS NUMBER(38,0),
    BLIND_POSITION_HANDS NUMBER(38,0),
    SHORT_STACK_HANDS NUMBER(38,0),
    DEEP_STACK_HANDS NUMBER(38,0),
    VPIP_RATE FLOAT,
    PFR_RATE FLOAT,
    AGGRESSION_FREQUENCY FLOAT,
    CALL_PREFERENCE FLOAT,
    FLOP_CBET_RATE FLOAT,
    TURN_BARREL_RATE FLOAT,
    RIVER_SEEN_RATE FLOAT,
    ALL_IN_RATE FLOAT,
    AVG_PREFLOP_RAISE_BB FLOAT,
    AVG_POSTFLOP_BET_POT_RATIO FLOAT,
    LATE_POSITION_VPIP_RATE FLOAT,
    BLIND_DEFEND_RATE FLOAT,
    SHORT_STACK_AGGRESSION_RATE FLOAT,
    DEEP_STACK_LOOSENESS FLOAT,
    SCORED_AT TIMESTAMP_NTZ
);

CREATE TABLE IF NOT EXISTS PROFILE_SESSION_RESULTS (
    MODEL_RUN_ID STRING,
    FEATURE_VERSION STRING,
    SOURCE_TYPE STRING,
    SOURCE_DATASET STRING,
    SOURCE_RUN_ID STRING,
    SIMULATION_RUN_ID STRING,
    SUBJECT_ID STRING,
    PLAYER_ID STRING,
    AGENT_ID STRING,
    HANDS_OBSERVED NUMBER(38,0),
    STATUS STRING,
    CLUSTER_ID NUMBER(38,0),
    CLUSTER_LABEL STRING,
    CONFIDENCE_SCORE FLOAT,
    SUMMARY_TEXT STRING,
    FEATURE_VECTOR VARIANT,
    TOP_FEATURE_DELTAS VARIANT,
    PROTOTYPE_MATCHES VARIANT,
    SCORED_AT TIMESTAMP_NTZ
);
