from __future__ import annotations

from profiles.constants import DEFAULT_TRAINING_DATASET, FEATURE_VERSION, MIN_TRAINING_HANDS


def profile_player_hand_features_sql(
    *,
    training_dataset: str = DEFAULT_TRAINING_DATASET,
    feature_version: str = FEATURE_VERSION,
    source_dataset: str | None = None,
) -> str:
    dataset_filter = ""
    if source_dataset:
        escaped_dataset = source_dataset.replace("'", "''")
        dataset_filter = f" AND a.SOURCE_DATASET = '{escaped_dataset}'"
    escaped_training_dataset = training_dataset.replace("'", "''")
    escaped_feature_version = feature_version.replace("'", "''")
    return f"""
CREATE OR REPLACE TABLE PROFILE_PLAYER_HAND_FEATURES AS
WITH base_actions AS (
    SELECT
        a.HAND_ID,
        a.SOURCE_RUN_ID,
        COALESCE(a.SOURCE_RUN_ID, '__null__') AS SOURCE_RUN_KEY,
        a.SOURCE_TYPE,
        a.SOURCE_DATASET,
        a.SIMULATION_RUN_ID,
        COALESCE(a.SIMULATION_RUN_ID, '__null__') AS SIMULATION_RUN_KEY,
        a.TABLE_ID,
        a.PLAYER_ID,
        a.AGENT_ID,
        COALESCE(NULLIF(a.POSITION, ''), 'UNKNOWN') AS POSITION,
        LOWER(a.STREET) AS STREET,
        LOWER(a.ACTION_TYPE) AS ACTION_TYPE,
        COALESCE(a.AMOUNT_BB, 0) AS AMOUNT_BB,
        COALESCE(a.POT_BEFORE_BB, 0) AS POT_BEFORE_BB,
        COALESCE(a.EFFECTIVE_STACK_BB, 0) AS EFFECTIVE_STACK_BB,
        COALESCE(a.IS_ALL_IN, FALSE) AS IS_ALL_IN,
        a.ACTION_INDEX,
        COALESCE(p.STACK_START_BB, a.EFFECTIVE_STACK_BB, 0) AS STACK_START_BB
    FROM CURATED_ACTIONS a
    LEFT JOIN CURATED_PLAYERS p
        ON a.HAND_ID = p.HAND_ID
       AND a.PLAYER_ID = p.PLAYER_ID
       AND COALESCE(a.SOURCE_RUN_ID, '__null__') = COALESCE(p.SOURCE_RUN_ID, '__null__')
       AND COALESCE(a.SIMULATION_RUN_ID, '__null__') = COALESCE(p.SIMULATION_RUN_ID, '__null__')
       AND a.SOURCE_TYPE = p.SOURCE_TYPE
       AND a.SOURCE_DATASET = p.SOURCE_DATASET
    WHERE a.SOURCE_TYPE = 'historical'
      AND a.PLAYER_ID IS NOT NULL
      {dataset_filter}
),
preflop_aggressor AS (
    SELECT
        HAND_ID,
        SOURCE_RUN_KEY,
        SOURCE_TYPE,
        SOURCE_DATASET,
        SIMULATION_RUN_KEY,
        TABLE_ID,
        PLAYER_ID
    FROM base_actions
    WHERE STREET = 'preflop'
      AND ACTION_TYPE IN ('bet', 'raise', 'all_in')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY HAND_ID, SOURCE_RUN_KEY, SOURCE_TYPE, SOURCE_DATASET, SIMULATION_RUN_KEY, TABLE_ID
        ORDER BY ACTION_INDEX DESC
    ) = 1
),
flop_first_aggressor AS (
    SELECT
        HAND_ID,
        SOURCE_RUN_KEY,
        SOURCE_TYPE,
        SOURCE_DATASET,
        SIMULATION_RUN_KEY,
        TABLE_ID,
        PLAYER_ID
    FROM base_actions
    WHERE STREET = 'flop'
      AND ACTION_TYPE IN ('bet', 'raise', 'all_in')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY HAND_ID, SOURCE_RUN_KEY, SOURCE_TYPE, SOURCE_DATASET, SIMULATION_RUN_KEY, TABLE_ID
        ORDER BY ACTION_INDEX ASC
    ) = 1
),
turn_first_aggressor AS (
    SELECT
        HAND_ID,
        SOURCE_RUN_KEY,
        SOURCE_TYPE,
        SOURCE_DATASET,
        SIMULATION_RUN_KEY,
        TABLE_ID,
        PLAYER_ID
    FROM base_actions
    WHERE STREET = 'turn'
      AND ACTION_TYPE IN ('bet', 'raise', 'all_in')
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY HAND_ID, SOURCE_RUN_KEY, SOURCE_TYPE, SOURCE_DATASET, SIMULATION_RUN_KEY, TABLE_ID
        ORDER BY ACTION_INDEX ASC
    ) = 1
),
per_hand AS (
    SELECT
        '{escaped_training_dataset}' AS TRAINING_DATASET,
        '{escaped_feature_version}' AS FEATURE_VERSION,
        b.SOURCE_TYPE,
        b.SOURCE_DATASET,
        b.SOURCE_RUN_ID,
        b.SIMULATION_RUN_ID,
        b.TABLE_ID,
        b.HAND_ID,
        b.PLAYER_ID,
        MAX(b.AGENT_ID) AS AGENT_ID,
        MAX(b.POSITION) AS POSITION,
        MAX(b.STACK_START_BB) AS STACK_START_BB,
        MAX(IFF(b.STREET = 'preflop' AND b.ACTION_TYPE IN ('call', 'bet', 'raise', 'all_in'), 1, 0))::BOOLEAN AS PREFLOP_VPIP,
        MAX(IFF(b.STREET = 'preflop' AND b.ACTION_TYPE IN ('bet', 'raise', 'all_in'), 1, 0))::BOOLEAN AS PREFLOP_PFR,
        SUM(IFF(b.ACTION_TYPE IN ('bet', 'raise', 'all_in'), 1, 0)) AS AGGRESSIVE_ACTIONS,
        SUM(IFF(b.ACTION_TYPE = 'call', 1, 0)) AS PASSIVE_ACTIONS,
        SUM(IFF(b.STREET = 'preflop' AND b.ACTION_TYPE IN ('bet', 'raise', 'all_in'), b.AMOUNT_BB, 0)) AS PREFLOP_AGGRESSIVE_AMOUNT_TOTAL_BB,
        SUM(IFF(b.STREET = 'preflop' AND b.ACTION_TYPE IN ('bet', 'raise', 'all_in'), 1, 0)) AS PREFLOP_AGGRESSIVE_ACTION_COUNT,
        SUM(IFF(b.STREET IN ('flop', 'turn', 'river') AND b.ACTION_TYPE IN ('bet', 'raise', 'all_in') AND b.POT_BEFORE_BB > 0, b.AMOUNT_BB / NULLIFZERO(b.POT_BEFORE_BB), 0)) AS POSTFLOP_AGGRESSIVE_BET_POT_RATIO_SUM,
        SUM(IFF(b.STREET IN ('flop', 'turn', 'river') AND b.ACTION_TYPE IN ('bet', 'raise', 'all_in') AND b.POT_BEFORE_BB > 0, 1, 0)) AS POSTFLOP_AGGRESSIVE_BET_COUNT,
        MAX(IFF(b.STREET IN ('flop', 'turn', 'river', 'showdown'), 1, 0))::BOOLEAN AS SAW_FLOP,
        MAX(IFF(b.STREET IN ('turn', 'river', 'showdown'), 1, 0))::BOOLEAN AS SAW_TURN,
        MAX(IFF(b.STREET IN ('river', 'showdown'), 1, 0))::BOOLEAN AS SAW_RIVER,
        MAX(IFF(b.IS_ALL_IN, 1, 0))::BOOLEAN AS ALL_IN
    FROM base_actions b
    GROUP BY
        b.SOURCE_TYPE,
        b.SOURCE_DATASET,
        b.SOURCE_RUN_ID,
        b.SIMULATION_RUN_ID,
        b.TABLE_ID,
        b.HAND_ID,
        b.PLAYER_ID
)
SELECT
    p.TRAINING_DATASET,
    p.FEATURE_VERSION,
    p.SOURCE_TYPE,
    p.SOURCE_DATASET,
    p.SOURCE_RUN_ID,
    p.SIMULATION_RUN_ID,
    p.TABLE_ID,
    p.HAND_ID,
    p.PLAYER_ID,
    p.AGENT_ID,
    p.POSITION,
    p.STACK_START_BB,
    p.PREFLOP_VPIP,
    p.PREFLOP_PFR,
    p.AGGRESSIVE_ACTIONS,
    p.PASSIVE_ACTIONS,
    p.PREFLOP_AGGRESSIVE_AMOUNT_TOTAL_BB,
    p.PREFLOP_AGGRESSIVE_ACTION_COUNT,
    p.POSTFLOP_AGGRESSIVE_BET_POT_RATIO_SUM,
    p.POSTFLOP_AGGRESSIVE_BET_COUNT,
    p.SAW_FLOP,
    p.SAW_TURN,
    p.SAW_RIVER,
    p.ALL_IN,
    IFF(p.SAW_FLOP AND pa.PLAYER_ID = p.PLAYER_ID, TRUE, FALSE) AS CBET_OPPORTUNITY_FLOP,
    IFF(p.SAW_FLOP AND pa.PLAYER_ID = p.PLAYER_ID AND fa.PLAYER_ID = p.PLAYER_ID, TRUE, FALSE) AS FLOP_CBET,
    IFF(p.SAW_TURN AND pa.PLAYER_ID = p.PLAYER_ID AND fa.PLAYER_ID = p.PLAYER_ID, TRUE, FALSE) AS TURN_BARREL_OPPORTUNITY,
    IFF(p.SAW_TURN AND pa.PLAYER_ID = p.PLAYER_ID AND fa.PLAYER_ID = p.PLAYER_ID AND ta.PLAYER_ID = p.PLAYER_ID, TRUE, FALSE) AS TURN_BARREL,
    IFF(p.POSITION IN ('CO', 'BTN'), TRUE, FALSE) AS LATE_POSITION_HAND,
    IFF(p.POSITION IN ('CO', 'BTN') AND p.PREFLOP_VPIP, TRUE, FALSE) AS LATE_POSITION_VPIP,
    IFF(p.POSITION IN ('SB', 'BB'), TRUE, FALSE) AS BLIND_POSITION_HAND,
    IFF(p.POSITION IN ('SB', 'BB') AND p.PREFLOP_VPIP, TRUE, FALSE) AS BLIND_DEFEND,
    IFF(p.STACK_START_BB <= 20, TRUE, FALSE) AS SHORT_STACK_HAND,
    IFF(p.STACK_START_BB <= 20, p.AGGRESSIVE_ACTIONS, 0) AS SHORT_STACK_AGGRESSIVE_ACTIONS,
    IFF(p.STACK_START_BB <= 20, p.PASSIVE_ACTIONS, 0) AS SHORT_STACK_PASSIVE_ACTIONS,
    IFF(p.STACK_START_BB >= 80, TRUE, FALSE) AS DEEP_STACK_HAND,
    IFF(p.STACK_START_BB >= 80 AND p.PREFLOP_VPIP, TRUE, FALSE) AS DEEP_STACK_VPIP,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS UPDATED_AT
FROM per_hand p
LEFT JOIN preflop_aggressor pa
    ON p.HAND_ID = pa.HAND_ID
   AND COALESCE(p.SOURCE_RUN_ID, '__null__') = pa.SOURCE_RUN_KEY
   AND p.SOURCE_TYPE = pa.SOURCE_TYPE
   AND p.SOURCE_DATASET = pa.SOURCE_DATASET
   AND COALESCE(p.SIMULATION_RUN_ID, '__null__') = pa.SIMULATION_RUN_KEY
   AND p.TABLE_ID = pa.TABLE_ID
LEFT JOIN flop_first_aggressor fa
    ON p.HAND_ID = fa.HAND_ID
   AND COALESCE(p.SOURCE_RUN_ID, '__null__') = fa.SOURCE_RUN_KEY
   AND p.SOURCE_TYPE = fa.SOURCE_TYPE
   AND p.SOURCE_DATASET = fa.SOURCE_DATASET
   AND COALESCE(p.SIMULATION_RUN_ID, '__null__') = fa.SIMULATION_RUN_KEY
   AND p.TABLE_ID = fa.TABLE_ID
LEFT JOIN turn_first_aggressor ta
    ON p.HAND_ID = ta.HAND_ID
   AND COALESCE(p.SOURCE_RUN_ID, '__null__') = ta.SOURCE_RUN_KEY
   AND p.SOURCE_TYPE = ta.SOURCE_TYPE
   AND p.SOURCE_DATASET = ta.SOURCE_DATASET
   AND COALESCE(p.SIMULATION_RUN_ID, '__null__') = ta.SIMULATION_RUN_KEY
   AND p.TABLE_ID = ta.TABLE_ID
"""


def profile_player_training_features_sql(
    *,
    training_dataset: str = DEFAULT_TRAINING_DATASET,
    feature_version: str = FEATURE_VERSION,
    min_hands: int = MIN_TRAINING_HANDS,
) -> str:
    escaped_training_dataset = training_dataset.replace("'", "''")
    escaped_feature_version = feature_version.replace("'", "''")
    return f"""
CREATE OR REPLACE TABLE PROFILE_PLAYER_TRAINING_FEATURES AS
SELECT
    '{escaped_training_dataset}' AS TRAINING_DATASET,
    '{escaped_feature_version}' AS FEATURE_VERSION,
    PLAYER_ID,
    SOURCE_DATASET,
    COUNT(*) AS HANDS_PLAYED,
    SUM(AGGRESSIVE_ACTIONS) AS AGGRESSIVE_ACTIONS,
    SUM(PASSIVE_ACTIONS) AS PASSIVE_ACTIONS,
    SUM(IFF(CBET_OPPORTUNITY_FLOP, 1, 0)) AS FLOP_CBET_OPPORTUNITIES,
    SUM(IFF(TURN_BARREL_OPPORTUNITY, 1, 0)) AS TURN_BARREL_OPPORTUNITIES,
    SUM(IFF(LATE_POSITION_HAND, 1, 0)) AS LATE_POSITION_HANDS,
    SUM(IFF(BLIND_POSITION_HAND, 1, 0)) AS BLIND_POSITION_HANDS,
    SUM(IFF(SHORT_STACK_HAND, 1, 0)) AS SHORT_STACK_HANDS,
    SUM(IFF(DEEP_STACK_HAND, 1, 0)) AS DEEP_STACK_HANDS,
    (SUM(IFF(PREFLOP_VPIP, 1, 0)) + 1.0) / (COUNT(*) + 2.0) AS VPIP_RATE,
    (SUM(IFF(PREFLOP_PFR, 1, 0)) + 1.0) / (COUNT(*) + 2.0) AS PFR_RATE,
    IFF(SUM(AGGRESSIVE_ACTIONS) + SUM(PASSIVE_ACTIONS) > 0, SUM(AGGRESSIVE_ACTIONS) / NULLIFZERO(SUM(AGGRESSIVE_ACTIONS) + SUM(PASSIVE_ACTIONS)), 0.0) AS AGGRESSION_FREQUENCY,
    IFF(SUM(AGGRESSIVE_ACTIONS) + SUM(PASSIVE_ACTIONS) > 0, SUM(PASSIVE_ACTIONS) / NULLIFZERO(SUM(AGGRESSIVE_ACTIONS) + SUM(PASSIVE_ACTIONS)), 0.0) AS CALL_PREFERENCE,
    IFF(SUM(IFF(CBET_OPPORTUNITY_FLOP, 1, 0)) > 0, (SUM(IFF(FLOP_CBET, 1, 0)) + 1.0) / (SUM(IFF(CBET_OPPORTUNITY_FLOP, 1, 0)) + 2.0), 0.0) AS FLOP_CBET_RATE,
    IFF(SUM(IFF(TURN_BARREL_OPPORTUNITY, 1, 0)) > 0, (SUM(IFF(TURN_BARREL, 1, 0)) + 1.0) / (SUM(IFF(TURN_BARREL_OPPORTUNITY, 1, 0)) + 2.0), 0.0) AS TURN_BARREL_RATE,
    (SUM(IFF(SAW_RIVER, 1, 0)) + 1.0) / (COUNT(*) + 2.0) AS RIVER_SEEN_RATE,
    (SUM(IFF(ALL_IN, 1, 0)) + 1.0) / (COUNT(*) + 2.0) AS ALL_IN_RATE,
    IFF(SUM(PREFLOP_AGGRESSIVE_ACTION_COUNT) > 0, SUM(PREFLOP_AGGRESSIVE_AMOUNT_TOTAL_BB) / NULLIFZERO(SUM(PREFLOP_AGGRESSIVE_ACTION_COUNT)), 0.0) AS AVG_PREFLOP_RAISE_BB,
    IFF(SUM(POSTFLOP_AGGRESSIVE_BET_COUNT) > 0, SUM(POSTFLOP_AGGRESSIVE_BET_POT_RATIO_SUM) / NULLIFZERO(SUM(POSTFLOP_AGGRESSIVE_BET_COUNT)), 0.0) AS AVG_POSTFLOP_BET_POT_RATIO,
    IFF(SUM(IFF(LATE_POSITION_HAND, 1, 0)) > 0, (SUM(IFF(LATE_POSITION_VPIP, 1, 0)) + 1.0) / (SUM(IFF(LATE_POSITION_HAND, 1, 0)) + 2.0), 0.0) AS LATE_POSITION_VPIP_RATE,
    IFF(SUM(IFF(BLIND_POSITION_HAND, 1, 0)) > 0, (SUM(IFF(BLIND_DEFEND, 1, 0)) + 1.0) / (SUM(IFF(BLIND_POSITION_HAND, 1, 0)) + 2.0), 0.0) AS BLIND_DEFEND_RATE,
    IFF(SUM(SHORT_STACK_AGGRESSIVE_ACTIONS) + SUM(SHORT_STACK_PASSIVE_ACTIONS) > 0, SUM(SHORT_STACK_AGGRESSIVE_ACTIONS) / NULLIFZERO(SUM(SHORT_STACK_AGGRESSIVE_ACTIONS) + SUM(SHORT_STACK_PASSIVE_ACTIONS)), 0.0) AS SHORT_STACK_AGGRESSION_RATE,
    IFF(SUM(IFF(DEEP_STACK_HAND, 1, 0)) > 0, (SUM(IFF(DEEP_STACK_VPIP, 1, 0)) + 1.0) / (SUM(IFF(DEEP_STACK_HAND, 1, 0)) + 2.0), 0.0) AS DEEP_STACK_LOOSENESS,
    IFF(COUNT(*) >= {int(min_hands)}, TRUE, FALSE) AS ELIGIBLE_FOR_TRAINING,
    CURRENT_TIMESTAMP()::TIMESTAMP_NTZ AS UPDATED_AT
FROM PROFILE_PLAYER_HAND_FEATURES
WHERE TRAINING_DATASET = '{escaped_training_dataset}'
  AND FEATURE_VERSION = '{escaped_feature_version}'
GROUP BY PLAYER_ID, SOURCE_DATASET
"""
